"#ifndef _RENDER_PBR_STRUCTURES_FXH_\n"
"#define _RENDER_PBR_STRUCTURES_FXH_\n"
"\n"
"// #include \"BasicStructures.fxh\"\n"
"// #include \"PBR_Structures.fxh\"\n"
"\n"
"#ifndef COMPUTE_MOTION_VECTORS\n"
"#   define COMPUTE_MOTION_VECTORS 0\n"
"#endif\n"
"\n"
"struct PBRFrameAttribs\n"
"{\n"
"    CameraAttribs               Camera;\n"
"    CameraAttribs               PrevCamera; // Previous frame camera used to compute motion vectors\n"
"    PBRRendererShaderParameters Renderer;\n"
"\n"
"#if defined(PBR_MAX_LIGHTS) && PBR_MAX_LIGHTS > 0\n"
"    PBRLightAttribs Lights[PBR_MAX_LIGHTS];\n"
"#endif\n"
"\n"
"#if defined(ENABLE_SHADOWS) && ENABLE_SHADOWS && defined(PBR_MAX_SHADOW_MAPS) && PBR_MAX_SHADOW_MAPS > 0\n"
"    PBRShadowMapInfo ShadowMaps[PBR_MAX_SHADOW_MAPS];\n"
"#endif\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(PBRFrameAttribs);\n"
"#endif\n"
"\n"
"\n"
"struct PBRPrimitiveAttribs\n"
"{\n"
"    GLTFNodeShaderTransforms Transforms;\n"
"#if COMPUTE_MOTION_VECTORS\n"
"    float4x4                 PrevNodeMatrix;\n"
"#endif\n"
"    PBRMaterialShaderInfo    Material;\n"
"\n"
"    float4 CustomData;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(PBRPrimitiveAttribs);\n"
"#endif\n"
"\n"
"struct PBRHeightmapAttribs\n"
"{\n"
"    float ScaleX;\n"
"    float ScaleY;\n"
"    float OffsetX;\n"
"    float OffsetY;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(PBRHeightmapAttribs);\n"
"#endif\n"
"\n"
"struct PBRInstanceAttribs\n"
"{\n"
"    float4x4            NodeMatrix;\n"
"    PBRHeightmapAttribs HeightmapAttribs;\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"	CHECK_STRUCT_ALIGNMENT(PBRInstanceAttribs);\n"
"#endif\n"
"\n"
"#endif // _RENDER_PBR_STRUCTURES_FXH_\n"
