name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

# libsdl2-dev is not directly supported
#    - name: install_dependencies
#      run: sudo apt-get install libsdl2-dev

    - name: Build
      run: make disasOV1 disasOV2
